apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: flask
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sluetzen-tenant/flask/flask@sha256:9ddad956046d44ce367b9c82c8635a69b9e4e873b03b26cc52c1be38f4f4092d
        name: my-python
        resources: {}
status: {}
