apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: flask
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flask
    app.kubernetes.io/part-of: flask
  name: flask8ev7
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: flask
    weight: null
status: {}
