apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: flask
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flask
    app.kubernetes.io/part-of: flask
  name: flask
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: flask
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sluetzen-tenant/flask/flask@sha256:64de7621841f9bc2793083f1a5aeda0b9fb13e08596be3577c90a160c2b50bba
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
